[package]
name = "rustgame"
version = "0.1.0"
edition = "2024"
default-run = "rustgame"

[dependencies]
sdl2 = { version = "0.38.0" }
png = "0.17"

[lib]
name = "rustgamex"
path = "src/lib.rs"

[[bin]]
name = "rustgame"
path = "src/main.rs"

[[bin]]
name = "level_editor"
path = "src/bin/level_editor.rs"
